import React, { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import {
  Share2, Link, X, Copy, Check, Mail, MessageCircle, FileText
} from 'lucide-react';
import useAppStore from '../../store/appStore';

function ShareOptionCard({ id, icon: Icon, customSvg, label, desc, onClick, active, colorClass }) {
  return (
    <motion.button
      id={id}
      onClick={onClick}
      whileHover={{ scale: 1.02, y: -1 }}
      whileTap={{ scale: 0.98 }}
      className={`w-full flex items-center gap-3 p-3 rounded-xl border border-border bg-white hover:border-primary-ring hover:shadow-xs transition-all text-left group ${colorClass}`}
    >
      <div className="w-10 h-10 rounded-xl bg-bg-subtle group-hover:bg-primary-light flex items-center justify-center text-ink-secondary group-hover:text-primary transition-colors flex-shrink-0">
        {customSvg ? customSvg : <Icon size={18} />}
      </div>
      <div className="flex-1 min-w-0">
        <p className="text-xs font-bold text-ink group-hover:text-primary transition-colors truncate">{label}</p>
        <p className="text-[11px] text-ink-muted truncate">{desc}</p>
      </div>
      {active && (
        <span className="text-xs font-bold text-emerald-600 bg-emerald-50 px-2 py-0.5 rounded-md border border-emerald-200">
          Done!
        </span>
      )}
    </motion.button>
  );
}

export default function ShareModal({ open, onClose, content = '' }) {
  const { addToast } = useAppStore();
  const [copiedLink, setCopiedLink] = useState(false);
  const [copiedMd, setCopiedMd] = useState(false);

  const preview = content.replace(/[#*`]/g, '').trim().slice(0, 180);

  // 1. Copy Web Link
  const copyLink = async () => {
    try {
      await navigator.clipboard.writeText(window.location.href);
      setCopiedLink(true);
      setTimeout(() => setCopiedLink(false), 2500);
      addToast('Web link copied to clipboard!', 'success');
    } catch { addToast('Copy failed', 'error'); }
  };

  // 2. Copy Formatted Markdown (for Notion, Slack, Docs)
  const copyMarkdown = async () => {
    try {
      await navigator.clipboard.writeText(content);
      setCopiedMd(true);
      setTimeout(() => setCopiedMd(false), 2500);
      addToast('Formatted Markdown copied! Perfect for Notion & Slack.', 'success');
    } catch { addToast('Copy failed', 'error'); }
  };

  // 3. Email / Gmail draft
  const shareEmail = () => {
    const subject = encodeURIComponent('Lenny AI Insight: Product & Growth');
    const body = encodeURIComponent(`${content}\n\n— Generated by Lenny AI\n${window.location.href}`);
    window.open(`mailto:?subject=${subject}&body=${body}`, '_self');
    onClose();
  };

  // 4. WhatsApp
  const shareWhatsApp = () => {
    const text = encodeURIComponent(`*Lenny AI Insight:*\n\n${content.slice(0, 500)}${content.length > 500 ? '...' : ''}\n\nRead full: ${window.location.href}`);
    window.open(`https://api.whatsapp.com/send?text=${text}`, '_blank');
    onClose();
  };

  // 5. X (Twitter)
  const shareTwitter = () => {
    const text = encodeURIComponent(`" ${content.replace(/[#*`]/g, '').slice(0, 200)}... "\n\nInsights via @LennyRachitsky AI`);
    window.open(`https://twitter.com/intent/tweet?text=${text}`, '_blank');
    onClose();
  };

  // 6. LinkedIn
  const shareLinkedin = () => {
    window.open(`https://www.linkedin.com/sharing/share-offsite/?url=${encodeURIComponent(window.location.href)}`, '_blank');
    onClose();
  };

  return (
    <AnimatePresence>
      {open && (
        <motion.div
          className="fixed inset-0 z-[110] flex items-center justify-center p-4"
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          exit={{ opacity: 0 }}
        >
          <motion.div className="absolute inset-0 bg-black/70 backdrop-blur-md" onClick={onClose} />
          <motion.div
            className="relative bg-[#181D2B] rounded-2xl shadow-[0_32px_80px_rgba(0,0,0,0.6)] w-full max-w-md z-10 overflow-hidden border border-border"
            initial={{ opacity: 0, scale: 0.96, y: 16 }}
            animate={{ opacity: 1, scale: 1, y: 0 }}
            exit={{ opacity: 0, scale: 0.96, y: 8 }}
            transition={{ duration: 0.2, ease: [0.25, 1, 0.5, 1] }}
          >
            {/* Header */}
            <div className="flex items-center justify-between px-5 pt-4 pb-3 border-b border-border">
              <div className="flex items-center gap-3">
                <div className="w-9 h-9 rounded-xl bg-primary-light flex items-center justify-center">
                  <Share2 size={17} className="text-primary" />
                </div>
                <div>
                  <p className="text-sm font-bold text-ink leading-tight">Share & Export Answer</p>
                  <p className="text-[11px] text-ink-muted">Choose your preferred export or social format</p>
                </div>
              </div>
              <button onClick={onClose} className="btn-icon w-7 h-7">
                <X size={15} />
              </button>
            </div>

            {/* Preview Box */}
            {preview && (
              <div className="mx-5 mt-3.5 p-3 bg-bg-subtle rounded-xl border border-border/80">
                <p className="text-xs text-ink-secondary leading-relaxed line-clamp-2 italic font-serif">
                  "{preview}{content.length > 180 ? '…' : ''}"
                </p>
              </div>
            )}

            {/* Options List */}
            <div className="p-5 space-y-2 max-h-[380px] overflow-y-auto scrollbar-thin">
              {/* Copy Markdown */}
              <ShareOptionCard
                id="share-copy-md"
                icon={copiedMd ? Check : FileText}
                label="Copy as Markdown"
                desc="Ideal for pasting into Notion, Slack, Obsidian & Docs"
                onClick={copyMarkdown}
                active={copiedMd}
              />

              {/* Email / Gmail */}
              <ShareOptionCard
                id="share-email"
                icon={Mail}
                label="Send via Email / Gmail"
                desc="Draft an email with formatted text & source links"
                onClick={shareEmail}
              />

              {/* WhatsApp */}
              <ShareOptionCard
                id="share-whatsapp"
                customSvg={
                  <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="text-emerald-600">
                    <path d="M3 21l1.65-3.8a9 9 0 1 1 3.4 2.9L3 21" />
                    <path d="M9 10a.5.5 0 0 0 1 0V9a.5.5 0 0 0-1 0v1a5 5 0 0 0 5 5h1a.5.5 0 0 0 0-1h-1a.5.5 0 0 0 0 1" />
                  </svg>
                }
                label="Share on WhatsApp"
                desc="Send summary directly to contacts or groups"
                onClick={shareWhatsApp}
              />

              {/* Copy Link */}
              <ShareOptionCard
                id="share-copy-link"
                icon={copiedLink ? Check : Link}
                label="Copy Web Link"
                desc="Direct shareable link to this conversation"
                onClick={copyLink}
                active={copiedLink}
              />

              {/* Social Grid (X + LinkedIn) */}
              <div className="grid grid-cols-2 gap-2 pt-1">
                <button
                  onClick={shareTwitter}
                  className="flex items-center justify-center gap-2 p-2.5 rounded-xl border border-border bg-white hover:bg-bg-subtle text-xs font-semibold text-ink transition-all"
                >
                  <svg width="14" height="14" viewBox="0 0 24 24" fill="currentColor">
                    <path d="M18.244 2.25h3.308l-7.227 8.26 8.502 11.24H16.17l-5.214-6.817L4.99 21.75H1.68l7.73-8.835L1.254 2.25H8.08l4.713 6.231zm-1.161 17.52h1.833L7.084 4.126H5.117z"/>
                  </svg>
                  Share on X
                </button>

                <button
                  onClick={shareLinkedin}
                  className="flex items-center justify-center gap-2 p-2.5 rounded-xl border border-border bg-white hover:bg-blue-50 hover:text-blue-600 hover:border-blue-200 text-xs font-semibold text-ink transition-all"
                >
                  <svg width="14" height="14" viewBox="0 0 24 24" fill="currentColor" className="text-blue-600">
                    <path d="M16 8a6 6 0 0 1 6 6v7h-4v-7a2 2 0 0 0-2-2 2 2 0 0 0-2 2v7h-4v-7a6 6 0 0 1 6-6zM2 9h4v12H2z"/><circle cx="4" cy="4" r="2"/>
                  </svg>
                  Share on LinkedIn
                </button>
              </div>

            </div>
          </motion.div>
        </motion.div>
      )}
    </AnimatePresence>
  );
}
